FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=on
ENV SHELL=/bin/bash

WORKDIR /

RUN apt update -y && \
    apt install -y --no-install-recommends \
    git wget python3.10-venv python3-pip

RUN ln -s /usr/bin/python3.10 /usr/bin/python

RUN wget -q https://github.com/coder/code-server/releases/download/v4.22.1/code-server-4.22.1-linux-amd64.tar.gz && \
    tar -xf code-server-4.22.1-linux-amd64.tar.gz && \
    rm code-server-4.22.1-linux-amd64.tar.gz && \
    ln -s ${PWD}/code-server-4.22.1-linux-amd64/bin/code-server /usr/local/bin/code-server

WORKDIR /workspace

CMD ["code-server", "--host", "0.0.0.0", "--auth", "none", "--port", "8888", "/workspace"]