FROM python:3.10-slim

RUN apt update && apt install git wget curl htop aria2 -y

RUN wget -q https://github.com/coder/code-server/releases/download/v4.91.1/code-server-4.91.1-linux-amd64.tar.gz && \
    tar -xf code-server-4.91.1-linux-amd64.tar.gz && \
    rm code-server-4.91.1-linux-amd64.tar.gz && \
    ln -s ${PWD}/code-server-4.91.1-linux-amd64/bin/code-server /usr/local/bin/code-server

WORKDIR /workspace

RUN mkdir -p ~/.local/share/code-server/User
RUN echo '{"workbench.colorTheme": "Visual Studio Dark", "workbench.startupEditor": "terminal"}' > ~/.local/share/code-server/User/settings.json


CMD ["code-server", "--host", "0.0.0.0", "--auth", "none", "--port", "8888", "--disable-workspace-trust","/workspace"]