# Stage 1: Download code-server
FROM alpine AS code-server-download
RUN apk add --no-cache curl
RUN curl -fL https://github.com/coder/code-server/releases/download/v4.97.2/code-server-4.97.2-linux-amd64.tar.gz | tar -C /usr/local/lib -xz
RUN mv /usr/local/lib/code-server-4.97.2-linux-amd64 /usr/local/lib/code-server

# Stage 2: Final image
FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive \
    NVIDIA_VISIBLE_DEVICES=all \
    NVIDIA_DRIVER_CAPABILITIES=all \
    HF_HUB_ENABLE_HF_TRANSFER=1

COPY --from=code-server-download /usr/local/lib/code-server /usr/local/lib/code-server
RUN ln -s /usr/local/lib/code-server/bin/code-server /usr/local/bin/code-server

# Install system packages
RUN apt-get update && apt-get install -y \
    git \
    wget \
    ffmpeg \
    libgl1 \
    libglib2.0-0 \
    aria2 \
    lz4 \
    --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip install nvitop huggingface_hub hf_transfer && pip cache purge
RUN code-server --install-extension ms-python.python

WORKDIR /workspace

RUN mkdir -p ~/.local/share/code-server/User
RUN echo '{"workbench.colorTheme": "Visual Studio Dark", "workbench.startupEditor": "none"}' > ~/.local/share/code-server/User/settings.json
    
CMD ["code-server", "--host", "0.0.0.0", "--auth", "none", "--port", "8888", "--disable-workspace-trust", "/workspace"]